const fs = require('fs');
const models = {
  'CandidatProfile': '<?php namespace App\\Models; use Illuminate\\Database\\Eloquent\\Factories\\HasFactory; use Illuminate\\Database\\Eloquent\\Model; class CandidatProfile extends Model { use HasFactory; protected  = []; public function user() { return ->belongsTo(User::class); } }',
  'RecruteurProfile': '<?php namespace App\\Models; use Illuminate\\Database\\Eloquent\\Factories\\HasFactory; use Illuminate\\Database\\Eloquent\\Model; class RecruteurProfile extends Model { use HasFactory; protected  = []; public function user() { return ->belongsTo(User::class); } public function jobOffers() { return ->hasMany(JobOffer::class, "recruteur_id"); } public function payments() { return ->hasMany(Payment::class, "recruteur_id"); } }',
  'JobOffer': '<?php namespace App\\Models; use Illuminate\\Database\\Eloquent\\Factories\\HasFactory; use Illuminate\\Database\\Eloquent\\Model; class JobOffer extends Model { use HasFactory; protected  = []; public function recruteur() { return ->belongsTo(User::class, "recruteur_id"); } public function applications() { return ->hasMany(Application::class); } public function quiz() { return ->hasOne(Quiz::class); } }',
  'Quiz': '<?php namespace App\\Models; use Illuminate\\Database\\Eloquent\\Factories\\HasFactory; use Illuminate\\Database\\Eloquent\\Model; class Quiz extends Model { use HasFactory; protected  = []; public function jobOffer() { return ->belongsTo(JobOffer::class); } public function questions() { return ->hasMany(Question::class); } }',
  'Question': '<?php namespace App\\Models; use Illuminate\\Database\\Eloquent\\Factories\\HasFactory; use Illuminate\\Database\\Eloquent\\Model; class Question extends Model { use HasFactory; protected  = []; protected  = ["options" => "array"]; public function quiz() { return ->belongsTo(Quiz::class); } }',
  'Application': '<?php namespace App\\Models; use Illuminate\\Database\\Eloquent\\Factories\\HasFactory; use Illuminate\\Database\\Eloquent\\Model; class Application extends Model { use HasFactory; protected  = []; public function jobOffer() { return ->belongsTo(JobOffer::class); } public function candidat() { return ->belongsTo(User::class, "candidat_id"); } }',
  'Payment': '<?php namespace App\\Models; use Illuminate\\Database\\Eloquent\\Factories\\HasFactory; use Illuminate\\Database\\Eloquent\\Model; class Payment extends Model { use HasFactory; protected  = []; public function recruteur() { return ->belongsTo(User::class, "recruteur_id"); } }'
};
Object.keys(models).forEach(m => fs.writeFileSync('app/Models/'+m+'.php', models[m]));
